# 1 Векторы, Матрицы, Массивы

## 1.1 Создание вектора в Numpy
## Задача
Требуется создать вектор

In [6]:
import numpy as np

In [7]:
# Вектор строка
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [8]:
# Вектор столбец
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_column

array([[1],
       [2],
       [3]])

## 1.2 Создание матрицы
## Задача
Требуется создать матрицу

In [10]:
# Матрица с исп Двумерного массива (array)
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])
matrix
# print(type(matrix))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [11]:
# Матрица с исп матричную структуру (mat)
matrix_second = np.mat([[1,2],
                       [1,2],
                       [1,2]])
matrix_second
# print(type(matrix_second))

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [12]:
# Однако матричная структура данных не рекомендуется по двум причинам. 
# Во-первых, массивы являются де-факто стандартной структурой данных NumPy. 
# Во-вторых, подавляющее большинство операций NumPy возвращают не матричные 
# объекты, а массивы.

## 1.3 Создание разреженной матрицы (CSR - compressed sparse row)
## Задача
Имеются данные с очень малым количеством ненулевых значений, которые требуется эффективно представить

In [14]:
from scipy import sparse

matrix_third = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_sparse = sparse.csr_matrix(matrix_third)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


## 1.4. Выбор элементов
## Задача
Требуется выбрать один или несколько элементов в векторе или матрице.

In [16]:
# Создать вектор-строку
vector = np.array([1,2,3,4,5])
# Создать матрицу
matrix_fourth = np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9]])
# Выбрать третий элемент вектора
print(vector[2])
# Выбрать вторую строку, второй столбец 
print(matrix_fourth[1,1])

3
5


In [17]:
# Срезы в numpy

# Выбрать все элементы вектора
vector[:]
# Выбрать все вплоть до третьего элемента включительно 
vector[:3]
# Выбрать последний элемент
vector[-1]
# Выбрать первые две строки и все столбцы матрицы
matrix_fourth[:2,:]
# Выбрать все строки и второй столбец
matrix_fourth[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5. Описание матрицы 
## Задача

Требуется описать форму, размер и размерность матрицы.

In [19]:
matrix_five = np.array([[1,2,3,4],
                        [5,6,7,8],
                        [14,13,11,12]])
# Взглянуть на количество строк и столбцов
matrix_five.shape
# Взглянуть на количество элементов (строки * столбцы)
matrix_five.size
# Взглянуть на количество размерностей
matrix_five.ndim

2

## 1.6. Применение операций к элементам
## Задача
Требуется применить некоторую функцию к нескольким элементам массива.

In [21]:
matrix_six = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
# Создать функцию, которая добавляет к чему-то 100
add_100 = lambda i: i + 100
# Создать векторизованную функцию
vectorized_add_100 = np.vectorize(add_100)
# Применить функцию ко всем элементам в матрице
vectorized_add_100(matrix_six)


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Нахождение максимального и минимального значений + (axis)
## Задача
Требуется найти максимальное и минимальное значение в массиве

In [23]:
# Создать матрицу
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Вернуть максимальный элемент 
np.max(matrix)
# Вернуть минимальный элемент 
np.min(matrix)


1

## 1.8  Вычисление среднего значения дисперсии и стандартного отклонения (mean,var,std)
## Задача
Требуется вычислить некоторые описательные статистические показатели о массиве

In [48]:
matrix_seven = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
# Вернуть среднее значение
np.mean(matrix_seven)
# Вернуть дисперсию 
np.var(matrix_seven)
# Вернуть стандартное отклонение
np.std(matrix_seven)

2.581988897471611

## 1.9 Реформирование массивов (reshape)
## Задача
Требуется изменить форму массива без изменения значений элементов

In [75]:
# Создать матрицу 4x3
matrix_eight = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [ 10, 11 , 12 ]])
# Реформировать матрицу в матрицу 2x6
matrix_eight.reshape(2, 6)
matrix_eight.reshape(1,-1)
matrix_eight.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.10 Транспонирование ветора в матрицу (T)
## Задача
Требуется транспонировать веткор в матрицу

In [97]:
matrix.T
# Транспонировать вектор
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

## 1.11. Сглаживание матрицы (flatten)
## Задача
Требуется преобразовать матрицу в одномерный массив.

In [104]:
matrix_seven.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.12. Нахождение ранга матрицы (matrix_rank)
## Задача
Требуется узнать ранг матрицы.

In [110]:
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])
np.linalg.matrix_rank(matrix)

2

## 1.13. Генерирование случайных значений
## Задача
Требуется сгенерировать псевдослучайные значения.

In [115]:
# Задать начальное значение для генератора псевдослучайных чисел 
np.random.seed(0)
# Сгенерировать три случайных вещественных числа между 0.0 и 1.0 
np.random.random(3)
# Сгенерировать три случайных целых числа между 1 и 10 
np.random.randint(0, 11, 3)

array([3, 7, 9])